Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Style/FrozenStringLiteralComment:
  Enabled: false

AllCops:
  DisplayCopNames: true
  Exclude:
    - 'vendor/**/*'

Documentation:
  Enabled: false
